name: Build Cross-Platform Binaries

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.10.7  # Replace with your desired Python version

      - name: Check out code
        uses: actions/checkout@v3

      - name: Install pyinstaller
        run: pip install pyinstaller
        
      - name: Install dependencies
        run: pip install -r requirements.txt  # Adjust as needed

      - name: Build Binary
        run: pyinstaller --onefile --add-data "assets:assets" PyROE.py

      - name: Set executable bit for Linux and MacOS
        run: |
          if ($Env:RUNNER_OS -eq "Linux" -or $Env:RUNNER_OS -eq "macOS") {
            chmod +x dist/YourBinaryName
          }

      - name: Upload Binary
        uses: actions/upload-artifact@v3
        with:
          name: ${{ runner.os }}-binary
          path: dist/  # Adjust to match your build output directory
